### ISSUE TITLE
Add requirements to README file.

### ISSUE THREAD

**Issue by vigliensoni** [concordia-dcart/UE5_Dynamic_Synth#1]
Please add the requirements to the README file so that the configuration and set-up are clear to everyone wanting to play around with this repo.

**Comment by cavewerk** [comment]
I am currently cleaning up the project file, will update the readme following cleanup.

**Comment by cavewerk** [comment]
There is still more work to do, but is this clear enough for now? The blueprints/metasounds themselves are all commented out quite clearly.

**Comment by vigliensoni** [comment]
@cavewerk I'm opening the project with UE5 5.3.2 and it is asking me to Create a Copy. 

I believe we need to add the requirements to this file.
